import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — AKAI',
  description: 'Terms and conditions for using the AKAI platform.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white px-6 py-24">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-sm text-white/40 hover:text-white transition-colors mb-8 inline-block">← Back to home</Link>

        <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-2">Effective date: 22 April 2026 · Last updated: 22 April 2026</p>
        <p className="text-white/40 text-sm mb-12">
          <strong className="text-white/60">Operator:</strong> Aaron Kersten (ABN 50 179 250 215), trading as AKAI ·{' '}
          <a href="mailto:mrakersten@gmail.com" className="text-[#D4AF37] hover:underline">mrakersten@gmail.com</a> ·{' '}
          <a href="https://getakai.ai" className="text-[#D4AF37] hover:underline">getakai.ai</a>
        </p>

        <div className="prose prose-invert prose-sm max-w-none space-y-10 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By signing up for, accessing, or using AKAI (&quot;the Service&quot;), you (&quot;Client&quot;, &quot;you&quot;) agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree, do not use the Service.</p>
            <p className="mt-3">These Terms apply to all subscription plans, including free trials and beta access.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>AKAI is an AI-powered business automation platform that provides tools including but not limited to:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li>AI-assisted outbound and inbound voice calling (&quot;Sophie&quot;)</li>
              <li>Email monitoring, classification, and automated response drafting</li>
              <li>Lead generation and research assistance</li>
              <li>Advertising campaign creation and management</li>
              <li>Social media content generation</li>
              <li>Website auditing and content generation</li>
              <li>Recruitment assistance</li>
              <li>Business intelligence and reporting</li>
            </ul>
            <p className="mt-4 text-white/90 font-semibold">AKAI is a tool to assist your business operations. It does not replace human judgement, legal advice, financial advice, or professional services of any kind.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Beta Service &amp; Early Access</h2>
            <p>AKAI is currently in <strong className="text-white">beta / early access</strong>. During this period:</p>
            <div className="mt-3 space-y-3">
              <p><strong className="text-white/80">3.1</strong> The Service is provided on a best-efforts basis. Features may change, be unavailable, or behave unexpectedly.</p>
              <p><strong className="text-white/80">3.2</strong> Free access during the beta period (up to 3 months where offered) is provided as a goodwill gesture and does not create any entitlement to continued free access or any specific feature set.</p>
              <p><strong className="text-white/80">3.3</strong> AKAI reserves the right to modify, suspend, or discontinue any feature or the Service itself with reasonable notice.</p>
              <p><strong className="text-white/80">3.4</strong> You acknowledge that as an early adopter you are using a product under active development.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. AI-Generated Content &amp; Outputs — Limitation of Liability</h2>
            <div className="bg-[#1a1a1a] border border-[#D4AF37]/30 rounded-xl p-4 mb-4">
              <p className="text-[#D4AF37] font-semibold text-sm">⚠️ This section is important. Please read carefully.</p>
            </div>
            <div className="space-y-3">
              <p><strong className="text-white/80">4.1</strong> <strong className="text-white">AI outputs are not guaranteed to be accurate, complete, or appropriate.</strong> All content generated by AKAI — including emails, call scripts, proposals, social media posts, advertising copy, lead data, reports, and recommendations — is produced by artificial intelligence and may contain errors, omissions, inaccuracies, or content that is inappropriate for your specific context.</p>
              <p><strong className="text-white/80">4.2</strong> <strong className="text-white">You are solely responsible for reviewing, approving, and taking responsibility for any content before it is sent, published, or acted upon.</strong> AKAI does not send communications on your behalf without your configuration and authorisation of the relevant automated workflows.</p>
              <p><strong className="text-white/80">4.3</strong> <strong className="text-white">AI voice calls made via Sophie</strong> are automated. You are responsible for ensuring:</p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Recipients have consented or are otherwise legally contactable in your jurisdiction</li>
                <li>Call scripts comply with applicable telecommunications, spam, and consumer protection laws</li>
                <li>You have obtained any required registrations, licences, or approvals for outbound calling in your jurisdiction</li>
              </ul>
              <p><strong className="text-white/80">4.4</strong> <strong className="text-white">AKAI is not responsible for:</strong></p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Any loss, damage, claim, liability, cost, or expense arising from the use of AI-generated content</li>
                <li>Any communication sent to a third party via the Service, including calls, emails, or messages</li>
                <li>Any regulatory breach, complaint, or penalty arising from your use of AI-generated communications</li>
                <li>Any business decision made in reliance on AKAI outputs</li>
                <li>Loss of data, revenue, profits, customers, reputation, or goodwill arising from use of the Service</li>
              </ul>
              <p><strong className="text-white/80">4.5</strong> <strong className="text-white">To the maximum extent permitted by law</strong>, AKAI&apos;s total aggregate liability to you for any claim arising from or related to the Service shall not exceed the total amount paid by you to AKAI in the 3 months preceding the claim, or AUD $100, whichever is greater.</p>
              <p><strong className="text-white/80">4.6</strong> Nothing in these Terms excludes liability that cannot be excluded by law (including under the Australian Consumer Law).</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Your Responsibilities</h2>
            <div className="space-y-3">
              <p><strong className="text-white/80">5.1</strong> You are responsible for all activity that occurs under your account.</p>
              <p><strong className="text-white/80">5.2</strong> You must not use AKAI to:</p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Send spam, unsolicited communications, or communications that violate applicable law</li>
                <li>Harass, threaten, or deceive any person</li>
                <li>Generate or distribute illegal, defamatory, or harmful content</li>
                <li>Impersonate any person or entity</li>
                <li>Conduct outbound calls or messages without appropriate consent or legal basis</li>
                <li>Violate any applicable law or regulation</li>
              </ul>
              <p><strong className="text-white/80">5.3</strong> You are responsible for maintaining the confidentiality of your account credentials.</p>
              <p><strong className="text-white/80">5.4</strong> You must ensure that your use of AKAI complies with all applicable laws in your jurisdiction, including but not limited to telecommunications law, spam/unsolicited communications law, consumer protection law, privacy law, and employment law.</p>
              <p><strong className="text-white/80">5.5</strong> You must not share API keys, account access, or credentials with unauthorised parties.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Data &amp; Privacy</h2>
            <div className="space-y-3">
              <p><strong className="text-white/80">6.1</strong> By using the Service you consent to AKAI processing data you provide or that is generated through your use of the Service, in accordance with our Privacy Policy.</p>
              <p><strong className="text-white/80">6.2</strong> Data processed through AKAI may be transmitted to third-party AI providers (including Anthropic) and communications platforms (including Bland.ai, Twilio) for the purpose of delivering the Service. These providers have their own data processing terms.</p>
              <p><strong className="text-white/80">6.3</strong> You retain ownership of your business data. AKAI may use anonymised, aggregated usage data to improve the Service.</p>
              <p><strong className="text-white/80">6.4</strong> You are responsible for ensuring you have appropriate rights and consents for any personal data you upload or process through AKAI, including contact lists used for outbound calling or emailing.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Intellectual Property</h2>
            <div className="space-y-3">
              <p><strong className="text-white/80">7.1</strong> AKAI and all related software, branding, and technology is owned by Aaron Kersten / AKAI. You are granted a limited, non-exclusive, non-transferable licence to use the Service during your subscription.</p>
              <p><strong className="text-white/80">7.2</strong> Content you provide to AKAI (e.g., your business information, branding, copy) remains your property.</p>
              <p><strong className="text-white/80">7.3</strong> AI-generated outputs created using your data and business context are provided to you for your use, subject to these Terms.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Payments &amp; Subscriptions</h2>
            <div className="space-y-3">
              <p><strong className="text-white/80">8.1</strong> Subscription fees are billed in advance on the applicable cycle (monthly or annual) via Stripe.</p>
              <p><strong className="text-white/80">8.2</strong> All fees are exclusive of applicable taxes (including GST where applicable).</p>
              <p><strong className="text-white/80">8.3</strong> Fees are non-refundable except as required by applicable law or as expressly stated in a promotional offer.</p>
              <p><strong className="text-white/80">8.4</strong> AKAI reserves the right to change pricing with 30 days&apos; notice. Continued use after the notice period constitutes acceptance of the new pricing.</p>
              <p><strong className="text-white/80">8.5</strong> Free trial periods, where offered, do not require payment details unless expressly stated.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Termination</h2>
            <div className="space-y-3">
              <p><strong className="text-white/80">9.1</strong> You may cancel your subscription at any time via the Settings page. Access continues until the end of the current billing period.</p>
              <p><strong className="text-white/80">9.2</strong> AKAI may suspend or terminate your account immediately if you breach these Terms, engage in fraudulent activity, or use the Service in a way that causes harm to others or to AKAI.</p>
              <p><strong className="text-white/80">9.3</strong> Upon termination, your access to the Service ceases. AKAI will retain your data for 30 days post-termination, after which it may be deleted.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Disclaimers</h2>
            <div className="space-y-3">
              <p><strong className="text-white/80">10.1</strong> THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</p>
              <p><strong className="text-white/80">10.2</strong> AKAI DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.</p>
              <p><strong className="text-white/80">10.3</strong> AI SYSTEMS CAN MAKE MISTAKES. AKAI DOES NOT WARRANT THE ACCURACY, COMPLETENESS, OR SUITABILITY OF ANY AI-GENERATED CONTENT.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Governing Law</h2>
            <p>These Terms are governed by the laws of New South Wales, Australia. Any disputes shall be subject to the exclusive jurisdiction of the courts of New South Wales, Australia.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Amendments</h2>
            <p>AKAI reserves the right to update these Terms at any time. Material changes will be notified via email or in-app notification at least 14 days before taking effect. Continued use of the Service after the effective date constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">13. Contact</h2>
            <p>For questions about these Terms:</p>
            <div className="mt-3 bg-[#111] border border-[#2a2a2a] rounded-xl p-4">
              <p className="font-semibold text-white">Aaron Kersten | AKAI</p>
              <p className="mt-1"><a href="mailto:mrakersten@gmail.com" className="text-[#D4AF37] hover:underline">mrakersten@gmail.com</a></p>
              <p><a href="https://getakai.ai" className="text-[#D4AF37] hover:underline">getakai.ai</a></p>
              <p className="text-white/40 text-sm mt-1">ABN 50 179 250 215</p>
            </div>
          </section>

          <div className="pt-8 border-t border-white/10">
            <p className="text-white/30 text-xs">Last updated: 22 April 2026</p>
          </div>

        </div>
      </div>
    </main>
  );
}
