export const metadata = {
  title: 'Terms of Service — AKAI',
  description: 'Terms and conditions for using the AKAI platform.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white px-6 py-24">
      <div className="max-w-3xl mx-auto">
        <a href="/" className="text-sm text-white/40 hover:text-white transition-colors mb-8 inline-block">← Back to home</a>

        <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: March 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance</h2>
            <p>By creating an account or using AKAI services, you agree to these Terms of Service. If you do not agree, do not use AKAI. These terms are governed by the laws of New South Wales, Australia.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. The service</h2>
            <p>AKAI provides AI-powered business automation tools including outbound calling, content generation, lead management, and related services. Features are provided &quot;as is&quot; and may change over time. We are currently in early access / beta.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Your responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Use AKAI only for lawful business purposes</li>
              <li>Ensure all contacts in your lead lists have opted in to receive communications</li>
              <li>Comply with the Australian Spam Act 2003 and Do Not Call Register Act 2006</li>
              <li>Not use AKAI to harass, deceive, or harm others</li>
              <li>Keep your account credentials secure</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Subscription and billing</h2>
            <p>AKAI subscriptions are billed monthly. A 7-day free trial is available on all plans. You may cancel at any time before your trial ends without charge. After the trial, cancellations take effect at the end of the current billing period. No partial refunds are provided.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. AI-generated content</h2>
            <p>Content generated by AKAI (including emails, social posts, proposals, and scripts) is provided as a starting point. You are responsible for reviewing and approving all AI-generated content before use. AKAI does not warrant that AI outputs are accurate, complete, or suitable for your specific purpose.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Outbound calling compliance</h2>
            <p>The Sophie AI calling system is designed for business-to-business and opted-in business-to-consumer outreach. You are responsible for ensuring your call lists comply with Australian Do Not Call Register requirements and relevant privacy laws. AKAI provides DNC compliance tools but cannot guarantee compliance if you override them.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Limitation of liability</h2>
            <p>To the maximum extent permitted by law, AKAI&apos;s liability is limited to the amount you paid for the service in the 3 months preceding the claim. We are not liable for indirect, consequential, or loss-of-profit damages.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Termination</h2>
            <p>We may suspend or terminate accounts that violate these terms. You may close your account at any time by contacting <a href="mailto:hello@getakai.ai" className="text-[#D4AF37] hover:underline">hello@getakai.ai</a>.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Contact</h2>
            <p>Questions? Email <a href="mailto:hello@getakai.ai" className="text-[#D4AF37] hover:underline">hello@getakai.ai</a> or write to AI Clozr, Sydney NSW, Australia.</p>
          </section>

        </div>
      </div>
    </main>
  );
}
