export const metadata = {
  title: 'Terms of Service — AKAI',
  description: 'Terms and conditions for using the AKAI platform.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white px-6 py-24">
      <div className="max-w-3xl mx-auto">
        <a href="/" className="text-sm text-white/40 hover:text-white transition-colors mb-8 inline-block">← Back to home</a>

        <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Effective date: 28 March 2026 · Last updated: 28 March 2026 · Governing law: New South Wales, Australia</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-10 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Agreement</h2>
            <p>By accessing or using the AKAI platform (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). AKAI is operated by AI Clozr (ABN 50 179 250 215), Sydney, New South Wales, Australia (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). If you are using AKAI on behalf of a business, you represent that you have authority to bind that business to these Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Service Description</h2>
            <p>AKAI is an AI-powered business automation platform. The Service includes, but is not limited to:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li><strong className="text-white">Autonomous email follow-ups</strong> — AKAI sends AI-drafted follow-up emails to your leads via your connected email account (Gmail or Microsoft Outlook)</li>
              <li><strong className="text-white">AI voice calls (Sophie)</strong> — AKAI places outbound voice calls to leads on your behalf via Bland.ai</li>
              <li><strong className="text-white">Calendar management</strong> — AKAI reads and writes your Google or Outlook calendar to schedule and book meetings</li>
              <li><strong className="text-white">Lead management</strong> — AKAI processes incoming enquiries, scores leads, and manages pipeline</li>
              <li><strong className="text-white">AI content generation</strong> — proposals, follow-up messages, and reports generated by AI</li>
              <li><strong className="text-white">Pattern learning</strong> — AKAI learns from your email and call data to improve response quality over time</li>
            </ul>
            <p className="mt-3">Features, pricing, and availability may change. We will provide reasonable notice of material changes.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Automated Communications</h2>
            <p>AKAI sends automated emails and makes automated phone calls on your behalf. By enabling these features, you explicitly acknowledge and agree to the following:</p>

            <h3 className="text-base font-semibold text-white/90 mt-4 mb-2">3.1 Permission to Send</h3>
            <p>You grant AKAI permission to send automated follow-up emails and make voice calls to individuals who have previously contacted you (your &quot;leads&quot;), using your connected email account and AKAI&apos;s calling infrastructure.</p>

            <h3 className="text-base font-semibold text-white/90 mt-4 mb-2">3.2 Unsubscribe Mechanism</h3>
            <p>Every automated email sent by AKAI on your behalf includes a functioning unsubscribe link. When a lead unsubscribes, AKAI records this preference and will not send further automated emails to that individual. You must honour all opt-out requests promptly and must not attempt to circumvent unsubscribe requests.</p>

            <h3 className="text-base font-semibold text-white/90 mt-4 mb-2">3.3 Sent on Your Behalf</h3>
            <p>Automated emails are sent using your connected email account (e.g., your Gmail or Outlook address). Your business name and email address appear as the sender. AKAI acts as your authorised agent for the purpose of sending these communications.</p>

            <h3 className="text-base font-semibold text-white/90 mt-4 mb-2">3.4 Your Responsibility</h3>
            <p>You are solely responsible for:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li>Ensuring you have a legitimate basis to contact each lead (e.g., the lead made an enquiry to your business, you have prior consent, or another lawful basis applies)</li>
              <li>Ensuring contacts are not on the Australian Do Not Call Register (for voice calls) or have otherwise opted out</li>
              <li>The content, accuracy, and appropriateness of all communications sent via AKAI</li>
            </ul>

            <h3 className="text-base font-semibold text-white/90 mt-4 mb-2">3.5 Applicable Laws</h3>
            <p>AKAI is designed to support compliance with the following laws. You are responsible for ensuring your use of AKAI meets the requirements of laws applicable to you:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li>Australian Spam Act 2003</li>
              <li>Do Not Call Register Act 2006 (Australia)</li>
              <li>Australian Privacy Act 1988 and the Australian Privacy Principles</li>
              <li>CAN-SPAM Act (where US recipients are involved)</li>
              <li>General Data Protection Regulation (GDPR) (where EU/UK recipients are involved)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. AI-Generated Content</h2>
            <p>AKAI uses large language models (currently Anthropic Claude) to generate email content, proposals, call scripts, and other business communications. By using these features, you acknowledge:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li><strong className="text-white">Content is AI-generated.</strong> Emails, proposals, and messages drafted by AKAI are created by artificial intelligence, not a human.</li>
              <li><strong className="text-white">You are responsible for accuracy.</strong> AI-generated content may contain errors, inaccuracies, or inappropriate language. You are responsible for reviewing content before it is sent, or for authorising auto-send and accepting responsibility for the output.</li>
              <li><strong className="text-white">Auto-send authorisation.</strong> When you enable autonomous follow-up mode, you authorise AKAI to send AI-generated emails without individual review. You accept full responsibility for the content of those emails.</li>
              <li><strong className="text-white">No legal or professional advice.</strong> AI-generated content does not constitute legal, financial, medical, or other professional advice.</li>
              <li><strong className="text-white">Pattern learning.</strong> AKAI may use anonymised data from your interactions (email responses, call outcomes) to improve its AI models. See our Privacy Policy for details.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Integrations</h2>
            <p>AKAI integrates with third-party services to deliver its features. By connecting an integration, you grant AKAI the access described below:</p>

            <h3 className="text-base font-semibold text-white/90 mt-4 mb-2">5.1 Google (Gmail & Calendar)</h3>
            <p>When you connect your Google account, AKAI requests permission to:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Read emails in your Gmail inbox to identify and process lead enquiries</li>
              <li>Send emails from your Gmail account on your behalf</li>
              <li>Read your Google Calendar to determine your availability</li>
              <li>Create and update events on your Google Calendar to book meetings</li>
            </ul>
            <p className="mt-2">AKAI&apos;s use of Google APIs complies with the <a href="https://developers.google.com/terms/api-services-user-data-policy" className="text-[#D4AF37] hover:underline" target="_blank" rel="noopener noreferrer">Google API Services User Data Policy</a>, including the Limited Use requirements.</p>

            <h3 className="text-base font-semibold text-white/90 mt-4 mb-2">5.2 Microsoft (Outlook)</h3>
            <p>When you connect your Microsoft account, AKAI requests permission to:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Read emails in your Outlook inbox to identify and process lead enquiries</li>
              <li>Send emails from your Outlook account on your behalf</li>
              <li>Read and write your Outlook calendar to manage meeting bookings</li>
            </ul>

            <h3 className="text-base font-semibold text-white/90 mt-4 mb-2">5.3 Bland.ai (Voice Calls)</h3>
            <p>AKAI uses Bland.ai to place AI voice calls to your leads. Call audio and outcomes are processed by Bland.ai and may be stored as call logs accessible within your AKAI dashboard. By enabling voice calls, you confirm you have authority to initiate calls to the contacts provided.</p>

            <p className="mt-4">You may disconnect any integration at any time via your account settings. Disconnecting an integration will stop AKAI from accessing that service, but will not delete data already collected.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Data Collection & Storage</h2>
            <p>AKAI collects and stores data necessary to provide the Service, including:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li><strong className="text-white">Account data</strong> — your name, email address, and business details</li>
              <li><strong className="text-white">Lead/enquiry data</strong> — names, email addresses, phone numbers, and message content of your leads, collected from your connected inbox</li>
              <li><strong className="text-white">Calendar data</strong> — event details and availability from your connected calendar</li>
              <li><strong className="text-white">Call data</strong> — call logs, durations, and outcomes from Bland.ai voice calls</li>
              <li><strong className="text-white">Usage data</strong> — platform interactions and AI engagement patterns</li>
            </ul>
            <p className="mt-3">Data is stored in Google Firestore. Your data is retained while your account is active and for 90 days following cancellation, after which it is deleted. We may retain data longer where required by law.</p>
            <p className="mt-2">For full details, see our <a href="/privacy" className="text-[#D4AF37] hover:underline">Privacy Policy</a>.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Subscriptions & Billing</h2>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li>Subscriptions are billed monthly in advance. Annual billing is available at a discount.</li>
              <li>A free trial may be available on first sign-up. Details are provided at registration.</li>
              <li>After the trial period, your chosen plan will be billed automatically.</li>
              <li>You may cancel at any time. Cancellation takes effect at the end of the current billing period. No partial refunds are issued.</li>
              <li>We reserve the right to modify pricing with 30 days&apos; written notice.</li>
              <li>All prices are in AUD unless stated otherwise. GST may apply.</li>
              <li>Payments are processed by Stripe. We do not store your payment card details.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Acceptable Use</h2>
            <p>You agree to use AKAI lawfully and ethically. You must not:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li>Use AKAI to send unsolicited bulk email (spam) or contact individuals without a legitimate basis to do so</li>
              <li>Contact individuals who have previously unsubscribed or opted out</li>
              <li>Use AKAI to contact individuals on the Do Not Call Register for voice call purposes without a lawful exemption</li>
              <li>Generate, distribute, or send misleading, deceptive, or illegal content</li>
              <li>Attempt to reverse-engineer, scrape, or circumvent any part of the platform</li>
              <li>Use AKAI to harass, threaten, or harm any individual or organisation</li>
              <li>Violate any applicable privacy law including the Australian Privacy Act 1988</li>
              <li>Misrepresent your identity or the nature of your communications to contacts</li>
              <li>Share account credentials with unauthorised parties</li>
            </ul>
            <p className="mt-3">We reserve the right to suspend or terminate accounts that violate these Terms without refund.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Intellectual Property</h2>
            <p>AKAI and all associated technology, software, and content is owned by us or our licensors. You are granted a limited, non-exclusive, non-transferable licence to use the Service for your internal business purposes.</p>
            <p className="mt-2">Content you create using AKAI (emails, proposals, scripts, social posts) remains yours. You grant us a licence to use anonymised, aggregated data to improve our AI models and service quality.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, AKAI and AI Clozr shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, revenue, data, or business opportunities, arising from your use of the Service.</p>
            <p className="mt-2">In particular, we are not liable for:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li>Decisions made by or actions taken based on AI-generated content, recommendations, or autonomous actions taken by the platform</li>
              <li>Inaccuracies in AI-generated emails, proposals, or other content</li>
              <li>Outcomes of autonomous email campaigns or voice calls conducted on your behalf</li>
              <li>Any regulatory penalties or legal claims arising from your use of automated communications</li>
              <li>Interruptions to third-party services (Google, Microsoft, Bland.ai, etc.)</li>
            </ul>
            <p className="mt-3">Our total liability to you for any claim arising from these Terms shall not exceed the total fees you paid us in the 3 months preceding the claim.</p>
            <p className="mt-2">Nothing in these Terms excludes liability for fraud, death or personal injury caused by negligence, or any liability that cannot be excluded by law, including under the Australian Consumer Law.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Warranties</h2>
            <p>The Service is provided &quot;as is&quot; without warranty of any kind. We do not warrant that the Service will be error-free, uninterrupted, or achieve specific business results. AI-generated content may be inaccurate — always review before sending where possible.</p>
            <p className="mt-2">Nothing in these Terms affects your rights under the Australian Consumer Law.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Indemnification</h2>
            <p>You agree to indemnify and hold harmless AKAI and AI Clozr from any claims, damages, losses, or costs (including legal fees) arising from: your use of the Service, your violation of these Terms, your violation of any third party&apos;s rights (including your leads&apos; privacy rights), or your breach of any applicable law including spam, privacy, or consumer protection legislation.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">13. Termination</h2>
            <p>Either party may terminate the agreement at any time. We may suspend or terminate your account immediately if you breach these Terms. You may cancel via your account settings or by emailing hello@getakai.ai.</p>
            <p className="mt-2">On termination, your data will be retained for 90 days and then deleted, unless we are required by law to retain it longer.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">14. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify you via email or in-app notification of material changes. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">15. Governing Law</h2>
            <p>These Terms are governed by the laws of New South Wales, Australia. Any disputes shall be subject to the exclusive jurisdiction of the courts of New South Wales, Australia.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">16. Contact</h2>
            <p>Questions about these Terms? Contact us at <a href="mailto:hello@getakai.ai" className="text-[#D4AF37] hover:underline">hello@getakai.ai</a> or write to AI Clozr (ABN 50 179 250 215), Sydney NSW Australia.</p>
          </section>

        </div>
      </div>
    </main>
  );
}
